### ISSUE TITLE
Make sure TKLBAM is backing up correct data

### ISSUE THREAD

**Issue by DocCyblade** [l-arnold/tkl-nomadic-odoo#14]
Need to make sure TKLBAM will backup any user data (attachments, samba folders if kept)

**Comment by l-arnold** [comment]
OK.  I did just move my Database from a build a few months ago into New Build.

Problem w/ TKLBAM is there need to be "ap ids" created which I don't think there is for Odoo.  It might take the Lapp ID.

I can try a test.

**Comment by l-arnold** [comment]
Moved the Database with the Odoo Manage Databases interface.  (Backup from Old, Restore to new).  Was somewhat worried things would break.  I think there should often be some SQL commands in case data structures have changed along the way with GIT Changes.  I will research that as well.

**Comment by l-arnold** [comment]
Good Point about Samba.  I think it would pick this up by default.  Big part of TKLBAM is defining which folders "not" to backup, ie, those that are built by the install.

**Comment by l-arnold** [comment]
Update Process (to consider) when Code Base is moved forward on an older Database.
It is possible that the database structure has changed.  I do not know if Odoo will AUTO Fix the Database to new "basis".

This command appears to be "of what I was recalling" that has to do with Updating a DB correctly.  It is calling the openerp-server.conf file (not odoo as here).  Also need to see if this can run while server is running or does it need to be "new".  Our system is not "by default" opening a Database, so it should be able to be run before the Database is invoked (at restoration point)

sudo -u odoo /opt/odoo/odoo-server/openerp-server -d "DB-NAME" -u all  --config=/etc/odoo-server.conf

**Comment by l-arnold** [comment]
Making sense of an old email:  Version 7

"Most errors gone on try 2 and after Grafting a few inputs together.

./openerp-server -c /etc/openerp-server.conf -u all -d YOURDATABASENAME  (random web instructions)
-u all sale_payment_method,connector  ( Guewen's instructions on this list from Feb 10 2014 )

what is working for database upgrade right now is:  (very long upgrade seems to have completed - and no running errors that I can see as last time)
su - openerp
/bin/bash start -u all 

can test again: (had an error on first try - seem to have installed the modules below automatically 7.0.0.2.1.)
su - openerp
/bin/bash start -u all sale_payment_method,connector"

**Comment by DocCyblade** [comment]
Some good info from another issue https://github.com/l-arnold/tkl-nomadic-odoo/issues/18#issuecomment-137865312

**Comment by l-arnold** [comment]
I need to drop into the Instructions from @JedMeister Jedmeister still.  That was a great start to the subject.

The question of "how to upgrade" versions should not be the current issue.  I would like to solve that in the future.

We may want to consider "releases" rather than "git" so our "ground zero" is simpler to objectify.  realistically though, I think TKLBAM will move us forward.  We may want an "update script" as part of "Tklbam" restore perhaps.

**Comment by l-arnold** [comment]
Jedmeister's comment (from Issues/Oddo new Appliance thread)

@JedMeister 
(your great note was) here

https://github.com/l-arnold/tkl-nomadic-odoo/issues/11

Re TKLBAM here are the steps.

Make sure that the core profile includes all the places where Odoo has data/etc stored. (Remember that inclusions are just a path; exclusions are preceeded with a -).
Fork & clone the TKLBAM profiles repo; create a new local branch, etc etc.
Create a new tklbam profile (call it the appliance name e.g. odoo). Inside that file create a list of any additional paths to include or exclude (remember excludes preceeded by -). If there are none then you can make it blank. You'll notice that most of them are blank although TBH I think that almost all apps probably have some sort of cache that could be excluded.... Job for another day...

**Comment by l-arnold** [comment]
how does TKLBAM know what profile to reference?  I assume there should be a matching entry in the "odoo" code base to line up with the "odoo" entry in TKLBAM?

Is it all about naming?
It seems this is "building" a system called "TurnKey Odoo".  My ConfigConsole seems to be following the "folder name structure" in TKLDEV so not quite getting the optics.  Webshell is giving me the same  "tkl-nomadic-dev".  I am sure we don't have that entered anywhere in the app build itself.

**Comment by l-arnold** [comment]
To answer my own question.  Something is telling TKLBAM we are alive.  Just went to run a test and got the following error:

TurnKey Hub Error: Backup profile archive not found: turnkey-odoo-14.0-jessie-amd64

I will submit the Pull Request for an empty Odoo Profile.  Just want to know if I should call it "odoo" or "turnkey-odoo" in my Branch and thus the Profile Directory ?

Thoughts?

**Comment by l-arnold** [comment]
Must be that naming it "odoo" will work.  There are no profiles starting with "turnkey" anywhere.

Changelog however does show this matching up with the "backup profile" error above:

turnkey-odoo-14.0 (1) turnkey; urgency=low

**Comment by l-arnold** [comment]
I will issue a pull request for the Tklbam profile and we can update the Changelog to reflect the proper format.  Seems logical.

**Comment by l-arnold** [comment]
Pull request issued for adding "odoo" to Tklbam-Packages (master)

**Comment by JedMeister** [comment]
Oops, I answered [your question above](https://github.com/l-arnold/tkl-nomadic-odoo/issues/14#issuecomment-138375741) (in part by linking to a [previous post](https://github.com/l-arnold/tkl-nomadic-odoo/issues/11#issuecomment-137302999)) but forgot to hit "comment"... Doh!

Sounds like you worked it out anyway... 

Also FWIW if you have very recently posted and no one has replied it can often make the thread more readable (and reduce email traffic) if you just edit your last post rather than making another new post. Also sometimes it's good to keep what you wrote previously but make it clear it's no longer relevant by striking it out ~~like this~~ - 2 tildes (~~) either side...

**Comment by l-arnold** [comment]
:+1:   Was wondering if "edit" was a good or a bad thing.  I try to put "parenthesis" (EDIT) if I have done so.  I don't believe "edits" transmit by email, but not sure.  ~~tildes are good if I can find them on my keyboard~~

**Comment by l-arnold** [comment]
@JedMeister :  Pull Request in https://github.com/turnkeylinux/tklbam-profiles needs to be closed to make a reasonable test on this.

I don't think anyone else is trying to BAM Odoo right now, so can we try it?

**Comment by JedMeister** [comment]
Unfortunately it's not just a case of merging the code. It will need to uploaded to the Hub too.

I suggest that you use the LAPP profile and test with that. TKLBAM will allow you to 'force' a specific profile. IIRC that should work in this instance...

**Comment by l-arnold** [comment]
@DocCyblade sounds like the odoo git will move in your process.

See the original here to see if any format is useful in the "mv" command:
https://github.com/l-arnold/tkl-odoo/blob/master/conf.d/30_odoo_installation

**Comment by l-arnold** [comment]
@JedMeister I will try to force Lapp.  Makes sense.
Lapp is also empty so shouldn't be any different.

**Comment by l-arnold** [comment]
Doing a Backup of Beta System running now with SSL CERTS applied.
Will see how restore goes when this is finished.

Used the --force-profile LAPP command (properly formatted) and backup has commenced.

**Comment by l-arnold** [comment]
@JedMeister Backup went well.  I recall this issue back when I was testing TKLDEV 14 on Lapp

EDIT:  SECOND TRY IN WEBSHELL (12320) SEEMS to have started without errors.  

THE ERROR BELOW is about WEBMIN/TKLBAM

Anyway, this is the Error in WEBMIN-TKLBAM  on RESTORE to a new system:
Error - Perl execution failed

syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 9, near "skip_packages skip_files skip_database limits)"
  (Might be a runaway multi-line () string starting on line 7)
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 12, near "}"
Can't use global @_ in "my" at /usr/share/webmin/tklbam/restore_run.cgi line 17, near "= @_"
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 38, near "}"
Can't use global @_ in "my" at /usr/share/webmin/tklbam/restore_run.cgi line 41, near "= @_"
syntax error at /usr/share/webmin/tklbam/restore_run.cgi line 50, near "}"

**Comment by l-arnold** [comment]
On restore "Stragglers" have come back to CONFCONSOLE.

CORRECTION
Main issues I see are: (~~) Pictures did not restore to Website(~~)
(~~)when IP was also transfered then Pictures Show Up.  Seem to be referenced to a Domain Name within ODOO.  (could be an Odoo Problem in my opinion, but if the DOMAIN name is reset within ODOO it will probably also TRANSFER.  AGAIN ODOO ISSUE THERE)(~~)

BELOW is IMPORTANT:
Passwords for ODOO User are not transfering properly.
(passwords can be reset via Postgresql).  I think I need to do that now.  (I DID AND WORKED)
(HOWEVER IF BIG SYSTEM individual users may need their passwords reset..  need to test)

SYSTEM PASSWORDS DO ENDURE.

Not sure if this is related to some "HASH" that was not transferred over.  Had this (password) situation happen once on a simple (internal odoo) backup/restore database process.

TRICK for PASSWORD RESET
trick is to Postrgres in and set a new password for the Users in "res_users"  by simply filling in a new password in the "blank" password field.  There is a "password_crypt" field that has data.  Who knows where that is set from.  Would be nice to move that across however in TKLBAM.

ALSO, PASSWORD RESET MECHANISM, WILL TEST.
WORKS for outside users.  Inside users often do not use "email address" to login, thus Reset email cannot be sent.  But this is something a User can work through on their Own.

Will still try to find out how to move Passwords through TKLBAM for Users.

**Comment by l-arnold** [comment]
To Sumarize.  We need Odoo Passwords to survive TKLBAM restore.  Seems some "hash" is involved that needs to be copied in in restore (or??)
Preexisting Database, existant before restore, passwords survive,
Restored Database (at least at first try) seems Passwords are unusable in prior form.

Everything else in TKLBAM seemed to work well.

**Comment by l-arnold** [comment]
Good Clue here, though I think my experience of just putting a "clear password" in user.res for my user works well.  Should work for any user.

https://www.odoo.com/forum/help-1/question/enable-password-recovery-from-database-42485

Alternatively, having Password Recovery enabled (and a post that everyone must "recover" their password works.

In USER Case, could also assign an Email rather than a name to their Login Name so they can use the Password Recovery if a direct Password does not want to be assigned.

Once one Admin is in, they can also generate Hashed passwords for every user and send via Email (and also have presented a Password reset link in the Admin panel that can be clicked directly).

(HOW IMPORTANT ARE BETTER SOLUTIONS TO THIS?)

**Comment by l-arnold** [comment]
It seems a "Odoo" Database Restore will reset the Hash on Password.  I need to test more but just put both a new and an old backup and was able to login.  The TKLBAM backup Database is "salvagable" but the Odoo Restored Databaes go quite easilty.

I think we should document this.

**Comment by l-arnold** [comment]
I believe I was WRONG about passwords not transmitting.  It seems I had lost track of the password I was in fact using.  

Just did a TKLBAM restore cycle again and am able to Log In with the old Password.  

I just tested on a second user also, and the old password is also passing.

Sorry for the false flag there yesterday.  Did learn how to get back in when a Password is lost anyway.

**Comment by l-arnold** [comment]
TKLBAM is RESTORING in SHELL very quickly and seemingly completely.

Only issue I am having I feel is a TKLBAM issue rather than this APP.  After Restore I have had a long run with Chrome repeatedly telling me that the Website I am visiting is "insecure".  I will "accept" then 2 pages later have to "accept again".  I expect this has to do with the "random" SSL SEED that TKL is putting down that changes.

I have no problems on the ODOO part of the system where I have my Own CERT applied.  This is only with the sections I do not apply that Cert, namely, EVERYWHERE ELSE.

Quite Aggravating.  Probably need to flush cash or apply my CERT more Widely.  Since I am testing I will try that now.

**Comment by l-arnold** [comment]
Not finding how to apply my cert to Webshell or Webmin.  I seem to have it for other parts accessible in Apache (these are not in Apache).

**Comment by l-arnold** [comment]
As I just noted on the Final To's Issue List
"TKLBAM is effectively backing up and restoring via Shell. The TKL Cert gets a little messy after wards. Certified CERt Works fine. All Data and Files move through very fast and without errors. Again NOTE the TKL Cert is messy afterwards though."

**Comment by l-arnold** [comment]
When TKLBAM is working as is based on LAPP, it is a COMPLETE restore.  this means that all of the "OLDER CODE" is being restored as well.  This is more of an issue for us right now as we assume there will be a TKL Release which is pretty stable.  However, if  ver 2 (14) is built etc etc, it becomes a potential way for Users to by pass Git Pull's.  That said, we would need to NOT RESTORE the code through TKLBAM Restore for this to work.

It is at this point that the Database Update (-d (database) -u (database) codes would need to kick in.

Also, What we "set as the MAP" of the TKL Appliance now needs to be Consistent into the Future.  So, where we put openerp-server.conf , specifically, needs to be called in TKLBAM Restore even if the CODE itself is Not called.

Let me know about "final mapping" directions for the Odoo Overlay.  I am doing a install right now with yesterdays PR's as a Test now.  Will try a BAM over the top and see the result as well.

**Comment by JedMeister** [comment]
My 2c says that for starters you have demonstrated that TKLBAM works... Doing a "full backup" of all the code and data (as it sounds like it does) IMO will be the most reliable and least likely to break... Then the user can upgrade/update their included version of Odoo themselves at their leisure and deal with anything that breaks then....

In the longer term we could look to tweak it to only include user data but I would suspect that that would get quite tricky to make it reliable across different versions of Odoo. IMO a larger backup that includes everything that it needs to (and some extra stuff it doesn't) and works; is far better than a very small backup that will only work under specific conditions...

**Comment by l-arnold** [comment]
Perfect.  I would like to Close this then.  Are we good?

**Comment by l-arnold** [comment]
premature button perhaps.
