### ISSUE TITLE
Follow current TKL conventions  (ie.  .art folder for current artwork)

### ISSUE THREAD

**Issue by l-arnold** [l-arnold/tkl-nomadic-odoo#16]
Review the setup, eg, for Magento build  (and others)

https://github.com/turnkeylinux-apps/magento/

Should likely trim some commentary files, (readme2.rst) for instance, here.

**Comment by JedMeister** [comment]
Following TKL conventions will make this quicker and easier to import into the TKL library. All this stuff will need to be done before we can include it...

**Comment by l-arnold** [comment]
Guessing the Artwork pattern is the same as the LAPP appliance as that is where anything came from.

**Comment by JedMeister** [comment]
Check out the templates: https://github.com/turnkeylinux/artwork/tree/master/templates 
You'll at least want a logo.png screenshots are a bonus.

**Comment by l-arnold** [comment]
I will start on the links after we close the Pull Request in branch: dev-wip1
If I could get some help on renaming the folder in Shell.  Last time I tried to do that I mucked everything up.  Perhaps I could do in web interface just making a new folder, but I think easier with the MV command in shell.

**Comment by JedMeister** [comment]
@l-arnold - what do you mean "renaming a folder in shell"? You use the `mv` command to move/rename files or directories. 

When you are working in a git repo it's probably a good idea to do a `git mv` so that git knows what is happening (otherwise it will think that you deleted the old path and created a new path).

**Comment by l-arnold** [comment]
Just understand that the images folder prob needs to be moved/or/renamed "Art" or simular to the new TKL convention.

Need to check my notes but I had thought mv images art would do iy.  Buy as I noted our giy got messed up around thos subject last week on a diff rename/move.   

Looks like I made the mistake of "mv" and not"git mv".  Thanks for that clarification.  Was just following some similar "mv" I had done before.

Thanks Jeremy. 

Landis

**Comment by l-arnold** [comment]
Thumbs on a phone.  Will fix text later.

**Comment by JedMeister** [comment]
Also FYI git won't track an empty directory. I notice that your repo does not appear to have a `.art` dir but perhaps it does locally and git just isn't tracking it yet (because it's empty)?

**Comment by l-arnold** [comment]
Thanks Jeremy.  Reading my mind. Vi almost suggeated a move like that but realized github won't even let you create an empty directory.

Haven't declared the folder. 

Will try Git Move.  Solved my trepidation with that command.

**Comment by l-arnold** [comment]
Well. Not really successful.
Not only did "git mv" not work I proceeded to fall asleep.

Will be on project again early.

What sort of files are those templates?  How to open?  .kvf or soemething?

Thanks for your help @jedmeister.

**Comment by JedMeister** [comment]
.xcf - it's the native gimp format. Gimp is free open source image editor http://www.gimp.org/downloads/

Let me know about the issues when you have some more sleep :smile:

**Comment by l-arnold** [comment]
Thanks.  I've been meaning to test Gimp and some other OS programs in that space.

Big user of Libre Office, Open Office and some others.

Back at it..

**Comment by l-arnold** [comment]
Ok,
Worked through the git-mv
will change the few calls to the images folder next  (hope I can call "folders above"...  that is why images would normally be in the "www" folder in my opinion.  (Following the Magento example and put "art' into the "overlay" folder.

all on branch dev-wip1

**Comment by l-arnold** [comment]
@JedMeister  More complicated than I was expecting looking at the ".art" system.
Just now  looking in the github.com/turnkeylinux-apps/lapp for guidance

I see "art" is actually ".art" and not in "overlay" but in base level of the build.
Not seeing any calls to "logo.png" which is in the folder.
Not seeing any calls to 'turnkey_control_panel.jpg" which is also in the folder.

In the Odoo System, the only calls to the Images folder are in "index.php" which is the "Web Control Panel" that we are taking out.

Assuming another "git mv" cycle to the base level of the app,  how will "index.php" call that folder.  Is there some system variable that sets it.  Pretty sure index.php only knows how to look "around it".

Since Index.php will NOT be included, is it worth doing these changes at all?
Where does turnkey_control_panel.jpg get used?  Same for other ".art' in the system?

**Comment by l-arnold** [comment]
So,  I tried to "git mv" my (overlay/art) folder into (base level) ".art" folder (period up front).
Can't find the ".art" folder in my "base" (dev-wip1 - working folder).  After the commit, the "art" folder (no period) is still in the "overlay" folder from my last commit.
That folder, however is not in my Shell in that place now.  
Argh

This is my shell transcript:

root@tkldev products/dev-wip1# git mv overlay/art .art
root@tkldev products/dev-wip1# git push origin dev-wip1
Username for 'https://github.com': l-arnold
Password for 'https://l-arnold@github.com':
Everything up-to-date
root@tkldev products/dev-wip1# git commit -m '.art w/ period and in base via git mv and comit'
[dev-wip1 c6cb2af] .art w/ period and in base via git mv and comit
 2 files changed, 0 insertions(+), 0 deletions(-)
 rename {overlay/art => .art}/adminer_logo.png (100%)
 rename {overlay/art => .art}/odoo.png (100%)
root@tkldev products/dev-wip1# branch
-bash: branch: command not found
root@tkldev products/dev-wip1# git branch
dev-wip1
root@tkldev products/dev-wip1# dir
Makefile    README2.rst  changelog  dev-notes  plan
README.rst  build        conf.d     overlay    removelist

**Comment by l-arnold** [comment]
@JedMeister @DocCyblade 
Add to my last comment the following status:

root@tkldev products/dev-wip1# git status
On branch dev-wip1
Your branch is ahead of 'origin/dev-wip1' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean

**Comment by l-arnold** [comment]
Fixed it:  ALL GOOD Ran AGAIN  
git push origin dev-wip1

perhaps I missed the call for my username and password last time.

Working on the Index.php reference next.
Any more ".art" changes needed?  How do we logo this?  Perhaps we could have ODOO Logo in the Database Manager come up with a TKL-Odoo Logo but I have no idea how to do that.  Somewhere in the Odoo Code base I am sure.

**Comment by l-arnold** [comment]
Confirm, index.php not finding ".art" folder as a base at present.

Looked at "Lapp" build on Turnkeylinux-apps and it is still calling images in "images" folder but the images folder, likewise has moved to ".art" on top level.  I "doubt" but am not sure wheter it is connecting.  Would need some system variable to connect it seems.

In a "working" Odoo, I moved my Images manually to the same place and renamed to ".art"
index.php (which I am still using, based on LAPP) is not finding the images.  Tried moving the reference to the folder all together.  (tried dripping "images/"  tried referencing ".art/")

Is not the purpose of the .art folder to have other Images, like screenshots for the TurnkeyWebsite?  I don't really understand the whole "images is "ambiguous" change otherwise.  Seems like it is making work that doesn't really need to be done.  (Yes Screen Shots etc are Important to feed to the Turnkey Website).  It is just that HTML references like to go to an "images" or "art" folder in the base of the webroot, and not below that into the system).  Seems it could almost be a security issue.  If one is running Dreamweaver etc over SFTP they will need access to the whole system to get to ART.

**Comment by JedMeister** [comment]
@l-arnold as you discovered you need to commit first, then push!

It seems that you are a little confused. The `.art` and `images` directories are completely different and have different purposes.

The `images` directory (usually in the webroot, e.g. `/var/www/) is for images that will be provided by a webserver. These will often include things like adminer.png (adminer icon on tklwebcp) etc. 

The `.art` directory is for the TurnKey appliance page. It includes the appliance icon and some screenshots. This directory is not included in the appliance build!

E.g. the LAPP appliance icon (https://github.com/turnkeylinux-apps/lapp/blob/master/.art/logo.png) is the one displayed on the LAPP appliance page (http://www.turnkeylinux.org/lapp). Ther screenshots lower down are the ones from the apploiance `.art` directory.

**Comment by l-arnold** [comment]
I was only following the latest changes on the Lapp appliance where Images were moved (in my understanding) to the .art folder.  I thought I saw the same in Magento.

It seems I did not understand the Commit commentaries there.  I thought it indicated a "mv:".

Anyway,  will bring Images back and get .art working.  Makes sense to me and what I was essentially recomending.

**Comment by l-arnold** [comment]
Likely also that the moving of Adminer to Common took out the "images" that had Adminer to the Common build rather than the Turnkeylinuxapps/Lapp (etc) builds.

In any case, no Images folder left in the Lapp appliance code on GIT  that I could see.

**Comment by JedMeister** [comment]
That was ages ago. What is now `.art` used to (also) be called `images`. It was renamed (`mv`ed) to avoid confusion :smile: 

The images directory that contains the icons comes from common IIRC.

**Comment by l-arnold** [comment]
All good:

Last change to .art says this on commens:
.art    mv images .art (images is ambiguous)    a year ago   

Strange, the whole .art folder did not go into the Odoo Appliance though it was built off of Lapp.  That said, the whole build started more than a year ago..  so there we go.

All good.

**Comment by l-arnold** [comment]
Pulled a number of screen shots.  Will work on logos and uploading tommorrow.

**Comment by l-arnold** [comment]
(Update:  looks like my "white 3D Logo went missing).  Similar to the grey one below)

Logo created and committed
.art on branch dev-wip1

![logo](https://cloud.githubusercontent.com/assets/5673448/9718702/61149ce4-553b-11e5-8f32-5b4159777843.png)

![logo](https://cloud.githubusercontent.com/assets/5673448/9722475/27c76c3e-556b-11e5-8025-a4637a7122dc.png)

![logo-extrude-dark](https://cloud.githubusercontent.com/assets/5673448/9722479/3719a6d4-556b-11e5-8ccc-fe03ca18f738.png)

**Comment by l-arnold** [comment]
Screenshots Posted.  Here are some:
(Web console is listed as "Optional"
![odoo users inbox](https://cloud.githubusercontent.com/assets/5673448/9722177/a8db21d6-5565-11e5-9006-8d1e306e3d87.jpg)
![odoo crm - customer view](https://cloud.githubusercontent.com/assets/5673448/9722178/ae62bbe6-5565-11e5-8ef2-4a0a292c44b1.jpg)
![odoo crm opportunities](https://cloud.githubusercontent.com/assets/5673448/9722181/b2cb5738-5565-11e5-9102-18f82f220a22.jpg)
![odoo local modules available](https://cloud.githubusercontent.com/assets/5673448/9722182/b6e256fa-5565-11e5-84c7-59a1f3d35492.jpg)
![odoo web - magento modules](https://cloud.githubusercontent.com/assets/5673448/9722185/bc4ee89c-5565-11e5-8a04-f143d8d1492d.jpg)
![odoo quotations - sales and crm](https://cloud.githubusercontent.com/assets/5673448/9722190/c37d0d6a-5565-11e5-8f46-324854790709.jpg)
![odoo crm opportunities](https://cloud.githubusercontent.com/assets/5673448/9722191/ca41410c-5565-11e5-9343-2239edfcb6fb.jpg)
![optional web console](https://cloud.githubusercontent.com/assets/5673448/9722193/ce78e81a-5565-11e5-9168-733a35773793.jpg)

**Comment by l-arnold** [comment]
And Website Builder "preview"
![web site builder module in odoo](https://cloud.githubusercontent.com/assets/5673448/9722204/f7bb3d40-5565-11e5-9429-a0087dc3360a.jpg)

**Comment by l-arnold** [comment]
Web Console has been removed from Apache Sites Enabled.
Ok to still list this as "optional"

to "re-enable" from shell type:
           a2ensite odoo-12325.conf

**Comment by JedMeister** [comment]
Nice screenshots and I like the light grey odoo on dark grey icon... Very nice...

**Comment by l-arnold** [comment]
I can update any if need be.  Are we good to Close this issue re .art files and folders?

I want to be sure everything loads properly on next Pull request dev-wip1 <to> dev

**Comment by JedMeister** [comment]
I'm happy with what you've done! :+1:

**Comment by l-arnold** [comment]
Thanks Jeremy :smile:
