### ISSUE TITLE
Clean Webconsole  overlay/var/www/index.php 

### ISSUE THREAD

**Issue by l-arnold** [l-arnold/tkl-nomadic-odoo#17]
Alignment issue

overlay/var/www/index.php 

Probably too many entries

(this leads into cleaning documentation linked from Webconsole)

**Comment by JedMeister** [comment]
If I understand correctly this is the TKL landing page aka TKL Web Control Panel? (simple page that contains links to Webmin, Webshell, etc?

I know that you find this is a handy feature but it is not inline with TurnKey convention. TurnKey apps either have this sort of interface as the default "landing page" if you will; or they don't have it at all. IMO providing via a specific port (as you did IIRC) is not desirable for a regular app such as this.

**Comment by l-arnold** [comment]
Yes but functionally it is a "off center" Landing Page.

When going directly to the Site (port 80 or 443) one goes directly to Odoo.
However, I find that I often want to go to "other parts" of the system, and having a easy "way to get there" without typing the ports all the time is helpful.

To get to this "off center" Landing Page, you need to go to (https://ipaddress:12324) or (http://ipaddress:12325)

You can check  https www nomadic net : 12324 to see the interface and quick linkage.

One part is that this provides the potential for inbuild documentation (see link to the top right.)

**Comment by l-arnold** [comment]
@JedMeister Following up.  For me the console was invaluable in our debugging process this week.  Finding what was running right, what was not.  Checking this login, that login etc.  All were made very easy.

As far as I see there is Zero extra load on the system except for on Server File in Apache aiming at the "combined port set 12325 and 12324).

Personally, as a user, I would like this setup on EVERY TKL appliance.  It is really very practical in my opinion.  (I will leave this link briefly:  (can repost)

**Comment by l-arnold** [comment]
Updated the "Odoo" link Slightly.
Code for the Console is here:  (if you add "web" after the / it forces login - which I removed on my server but not the code base just now)
https://github.com/l-arnold/tkl-nomadic-odoo/blob/dev/overlay/var/www/index.php

**Comment by DocCyblade** [comment]
@l-arnold - I have a compromise. You can always have two branches, one using turnkey conventions, and another you can tweak the way you like. I do this with lamp/lapp all time and build custom builds my self. I would recommend going forward with getting this TKL ready. Once it is part of the master list, fork it and customize it to you're liking or keep this repo to customize to you're liking. 

Odoo from what I seen looks awesome, and would make a good appliance in the TKl library, so I would say focus on getting it TKL ready. @JedMeister can give you/us guidance on what would need to be changed or improved on before it would be included in the library. And I am more than willing to help you out when I can, just ask!

**Comment by l-arnold** [comment]
Certainly easy enough for me to bring the few settings in to mine even manually.  Really just was using what was in Lapp and "wishing I could keep it".  (For sure a branch is a good idea to keep track of the data set)

I'm good either way.  I've customized lots of builds and when things are working w/ TKLBAM they tend to move forward.

My old build I had on top of Lapp, so it was there all the time on Port 80 which I did not like.  Odoo was on 8069 before the Apache/Odoo proxy part started working, but instead of "deleting" I moved it to where I could still use it but it wouldn't jump at users.

**Comment by l-arnold** [comment]
My "mini tweak" above to keep away from login caused some issue on my site.  (only off of 12324 when linking (I removed the 3 letters "web", but will revert so from there login is forced).

Orig code:
-                <div>
-                      <a href="https://<?php print
-                       $_SERVER{'SERVER_NAME'}; ?>/web"><img
-                        src="images/odoo.png"/>Odoo Main (https)</a>
-                  </div> "

(sorry about the formatting above.. can't seem to fix)

 Seemed that removing "web" made it go to port 12324 .  Wierd.

**Comment by l-arnold** [comment]
Webconsole updated in "Pull Request"

**Comment by l-arnold** [comment]
Merged.   Propose leaving the .conf file even if it is not linked in "Apache" by default.

I would appreciate a little testing befor the "full boot" is given.  As I noted, makes me more productive anyway.  I am a believer in the "full TKL" system.
