### ISSUE TITLE
Potentially have a TKL mailing list for Odoo

### ISSUE THREAD

**Issue by l-arnold** [l-arnold/tkl-nomadic-odoo#19]
Seems that just as "security updates" can have a Mailing list so could other subjects.

A TKL Odoo Mailing list would seem a great way to build community and support for the platform.

**Comment by DocCyblade** [comment]
I think the mailing list option on first boot is for turnkey. Not sure TKL guys would want to send traffic or auto enroll people to an Odoo mailing list. I think if you are on the TKL mailing list and there is a major security alert for say lapp or something that TKL controls this would be the way they can reach out to people. Maybe on the web start console have some links that point to Odoo and their mailing list

**Comment by JedMeister** [comment]
Like Ken suggests the TurnKey "Security and News" mailing list is more of a (very low traffic) e-newsletter. It is just a way of us letting people know about really important (usually security related) TurnKey information. It is not designed to have anything to do with community.

I would suggest just using a "odoo" tag on the forums and/or a "turnkeylinux" tag on the Odoo forums (I don't know if Odoo forums support that?).

**Comment by l-arnold** [comment]
(Edited slightly)
My thought simply was a "TKL Mailing List" for different Apps.  (including Odoo).

I think engaging the community, sending out some pertinent info to their interests, could have merit.  Struck me really because I am sure I am on the "security updates" mailing list (in that I probably filled out the box 3 times now), but that there might be other things I am interested in.

True, if you go to TKL Website you can keep yourself informed.  That said, having some information come in your inbox can be engaging.

I have been to the Website and forums very little since starting on this project and things like a "weekly" or even "monthly mailing" might be reasonable.

I know it makes a lot of work for a small crew.

One rationale for "app specific" would have to do with "app specific" security updates.  I know these do come out.  Lets say Joomla or Magento have a real "issue",  but say only 10% of users use the Joomla and 8 % use Magento app, you would not want to send that info out to the whole TKL mailing list.  Among othe things you don't want to give the wide impression that TKL apps have security issues "by nature" which announcing "every one of 100 apps" security issues might very well create.

My thoughts only.

**Comment by l-arnold** [comment]
Closing for now.  Not an issue for this App right now.
