### ISSUE TITLE
Different "reset services" between Update Now (accept) and (Skip) directly before on Updates

### ISSUE THREAD

**Issue by l-arnold** [l-arnold/tkl-nomadic-odoo#21]
Needs clarification.

Had a troublesome build with updates.

**Comment by JedMeister** [comment]
Sry not really clear what you mean here?

**Comment by l-arnold** [comment]
Not sure it was a real observation.  It had seemed that the "reset services" cycle was throwing up a longer set of "script lines" right at the end of firstboot inithooks.  

On a second run, doing "security updates" (rather than skip) I had thought it was a longer set of "resets".  

In retrsospect I believe the security updates feed into the "reset services" and the actual scripting part from the reset was the same.  (hard thing to parse is all).

**Comment by l-arnold** [comment]
Will tag as a question  for now.

**Comment by DocCyblade** [comment]
To be honest I don't think I ever tested the updates. I always skip. Running a quick install

**Comment by DocCyblade** [comment]
@l-arnold I did see a difference, and the install updates updates the system. It does not look like the other script is being called after the updates are installed, now sure what is going on there.

It looks like `95secupdates` gets run, that calls `secupdates-ask.py` then  `install_updates` I think. Not sure why installing updates would cause the other inithook not to fire?

**Comment by l-arnold** [comment]
Ok.  I did see services (including) Openerp restart after install updates.
Probably need to test a few times.

Another reason to run a "snapshot" at System Restart during install.  Takes HD space but saves time.
Lets keep a focus on that.

Would love to have a "slow me down" check box somewhere.

**Comment by l-arnold** [comment]
Maybe move the "restart" services before the "install updates" to solve this.

**Comment by JedMeister** [comment]
Excuse my ignorance but why is this required? Apache should already be restarted when the [ssl-cert is regenerated](https://github.com/turnkeylinux/common/blob/master/overlays/turnkey.d/sslcert/usr/lib/inithooks/firstboot.d/15regen-sslcert#L25), postgres is restarted by the [inithook that sets the postgres & openerp passwords](https://github.com/turnkeylinux/common/blob/master/overlays/pgsql/usr/lib/inithooks/bin/pgsqlconf.py).

That only leaves odoo/openerp itself; why not make that a part of the [odoo inithook](https://github.com/l-arnold/tkl-nomadic-odoo/blob/dev/overlay/usr/lib/inithooks/bin/odoo.py)? Then you won't need the [97-odoo-restart-services inithook](https://github.com/l-arnold/tkl-nomadic-odoo/blob/dev/overlay/usr/lib/inithooks/firstboot.d/97-odoo-restart-services) at all...!? 

As an added bonus the odoo.py inithook will work standalone (whereas I suspect that currently it won't).

**Comment by l-arnold** [comment]
So after "install updates" I saw the "in and out" scripts.

During Skip it seemed a shorter set of notices.  Seems working anyway.

Are we good to close this?

**Comment by l-arnold** [comment]
Although we may have slight "optics" differential between with "updates" and without, the system is doing the services bounde and is working.

It is probable that much of the difficulty in getting the system running (by me, and later with ken) was the bug in the pgsqlconf.py file which was not reassigning the password to the postgres (and other postgresql) user(s).

The bounce system is reliable.   Ken and I discussed and it seems we can close this issue.

Jeremy's comment about using the Inithooks is taken.  We expect, again, that the bug in the inithook had us find a new course but in the situation, it was the only way to come out with a running system without a FULL REBOOT.
