### ISSUE TITLE
Manual Update Process (need correct permission)

### ISSUE THREAD

**Issue by l-arnold** [l-arnold/tkl-nomadic-odoo#22]
@DocCyblade 
(I'm a bit out of my element again)

Just brought in my old Database to a Build from the "Dev" level (no real changes)
However, wanting to run a "database" update at startup time.

In Webshell (su - openerp)  getting the following thread and errors.  Looks like the PID File should be owned by openerp  (correct)

openerp@tkl-nomadic-dev:/opt/openerp$ /bin/bash openerp.init restart -d nomad -u all
Restarting openerp-server: start-stop-daemon: unable to open pidfile '/var/run/openerp-server.pid'
for writing (Permission denied)
start-stop-daemon: child returned error exit status 2 (No such file or directory)
openerp@tkt-nomadic-dev:/opt/openerp$ I

**Comment by l-arnold** [comment]
Changing the owner of 

/var/run  points to /run
/run/openerp-server.pid   did not work.

It does cause "stragglers" at startup however.
Reset back to "root:root"

**Comment by DocCyblade** [comment]
I'll comment on this later tonight. Don't have much time right at the moment

**Comment by l-arnold** [comment]
No prob.  I'm wrestling w/ SSL.  Will comment separately on that one.  (so don't follow this one)

Can bring my SSL across pretty easily.  Just made the mistake of trying to mod 12324 and won't mod back.  (looking at how Apache nukes all this again)

**Comment by JedMeister** [comment]
Generally services should run as their own user; so I would assume "openerp"? Therefore pid/run files need to be owned by that particular user account...

**Comment by l-arnold** [comment]
I also thought that.  My experience was that when I made the owner "openerp" it created the "Stragglers" which had been messing with the confconsole.txt presentation for so long.

Will look a bit at the code.

What I am really trying to do is run a "manual startup" that updates an "restored" data file from Odoo.  

The command I was trying to run is:
 /bin/bash openerp.init restart -d nomad -u all

(nomad) is the name of the database.
-d (I assume means use database)
-u (I assume means "update")
(all, would assume "all" parts of the database.

(was wanting to work but giving the same error no matter who owned the .pid file in the error message (a few messages up now)

Just wanting to be sure my data files are up to snuff w/ current git pulls.  No errors and all migrated but "trust then verify".

**Comment by l-arnold** [comment]
Not sure this is critical for the TKL build. More of a "odoo" use question.

**Comment by DocCyblade** [comment]
@l-arnold I don't see openerp.init having those options. The code is just for starting and stopping the server. It in fact calls the openerp-server python script. Maybe these is another file your thinking of?

**Comment by l-arnold** [comment]
Likely the case.  Goes back to "version 7"..  difficult notes to decipher.  I will ask in the OCA branches.  
Pretty sure I needed to do this some time ago around the old Connector:

https://github.com/OCA/connector-magento

**Comment by JedMeister** [comment]
@l-arnold Ahh, now I understand what you mean by "stragglers" (TBH I was wondering...). So you mean the occasional lines of code that overwrite confconsole and/or the install screen? 

They are completely irrelevant to anything that you are doing. Any changes are purely coincidental... At this point we don't have a fix. They are caused by SystemD (it's a synchronous boot/init system whereas the previous SysVinit was asynchronous). Please see https://github.com/turnkeylinux/tracker/issues/338 & https://github.com/turnkeylinux/tracker/issues/356

**Comment by l-arnold** [comment]
In terms of "fix" or not I don't think we actually have a "problem" per say.  It is a course of inquiry.  I have not had any problems with my 3 x test migrations so far.

Just wanting to cover bases with the question.  I have seen issues in the past in the "OpenERP space" is all and was able to get fixed.  Just need to find the "backdoor" just in case.  If Odoo is doing it right, that "line of code" would be applied any time a Database is opened in Database Manager.

**Comment by l-arnold** [comment]
this is overlapping with issue:  Do have a question posted with one OCA community leader and should have info back soon.  (Will move to the following overlapping issue which also includes TKLBAM)
If an update command is desired it could also be integrated into a Odoo Specific TKLBAM script line.

https://github.com/l-arnold/tkl-nomadic-odoo/issues/18

Closing for now.
