### ISSUE TITLE
Look at Samba  (purposes, access, security)

### ISSUE THREAD

**Issue by l-arnold** [l-arnold/tkl-nomadic-odoo#24]
Working as we speak on a new Windows 10 machine.  No "Fileserver" showing itself.

Seems it was showing itself on Windows 7 (or similar last week).

Worth looking at this.  

Main issue, should it stay?  Should it go?

**Comment by JedMeister** [comment]
To be consistent with other appliances it should be removed IMO.

**Comment by l-arnold** [comment]
Given my "ongoing" issues around Windows Networking it probably makes sense simply from a Customer Service point of view not to put it in.

I won't go into further detail here.  Very aggravating though I will say.

Can we make a Branch that Isolates the single "take out" that I think would be required(that would float as the single act no matter what other changes occured later?

**Comment by l-arnold** [comment]
Summary of "current" accessibility to Odoo Fileserver and TKL PDC (Samba App)
- On this Windows 7 Client  "Fileserver"  (Samba current name on Odoo) shows up.  So does PDC Domain Controller (Samba Dedicated Controller).  Can log into both.
- Second Windows 7 Machine was not finding much the other day.  Some configuration issue.  Will try again.  Some "who knows what" setting needs to be set. Brand new install.  
- Windows 10 finds Windows Shares including FileServer and PDC (TKL DC).  PDC TKL DC will not open because of an unknown error..
- Windows 2008 Servers finds other Windows 2008 servers then slowly  PDC (TKL Domain Controller)
  Connects successfully to Both.  Odoo Fileserver with Root.  TKL PDC with Domain\Administrator
- Windows XP  (taken over by an endless internet explorer update process).  Will try to update soon.
- Windows 2000  (need timbuktu on XP to access)  Will try to update soon.

(I must say I like the idea of turning off a bunch of my "servers" floating around in various VM's.)

There is also a Windows 2000 PDC running (in NT Mode I believe - no DNS).  A few clients and attached servers also showing and opening on "most" machines to them as well.

**Comment by l-arnold** [comment]
The "unreliable" networking state of Windows sure makes me want to vote for Keeping Samba.  Every few hours I either have the full spread of "servers and workstations" showing or only a few.

Interestingly, Odoo Fileserver (samba) is the one that is consistently showing itself).  Even the TKL PDC (Samba in it but acting like a Domain Controller) comes and goes.

Will Look to see if I can "disable" it somehow but keep the code.  Does that seem reasonable?

**Comment by l-arnold** [comment]
ToDo Note:
Removing (or somehow commenting) these two lines in MAKEFILE should remove most of SAMBA.

-COMMON_OVERLAYS = tkl-webcp samba-fileserver samba-sid-inithook  
-COMMON_CONF = tkl-webcp fileserver-storage samba-rootpass samba-webmin     

Search SAMBA in the repository for other references.
Need to first do PR from dev-wip1 before this will be worked into dev-wip1 as it will confuse the system otherwise.

**Comment by JedMeister** [comment]
As I'm pretty sure I've said before I don't think that Odoo has a special case for including Samba (above any of the other appliances) so unless there is I don't see anyway of convincing Alon that it needs to stay (and that's only going to happen if you can convince me first! :smile:). 

Besides IMO there are far better ways to connect to Linux servers than default Windows ways IMO. E.g. SSHFS is far superior and is "internet safe" (i.e. is secure to use over the open internet) and all TurnKey appliances support it OOTB (no extras required). I suggest you install and check it out: This is the best fork AFAIK: https://github.com/dimov-cz/win-sshfs

**Comment by DocCyblade** [comment]
I will second remove samba from the mix. sshfs looks awesome :-)

**Comment by JedMeister** [comment]
@DocCyblade Mac being a nix-like system probably has a native build of SSHFS (from what I gather many/most nix tools are also available on OSX)...

**Comment by l-arnold** [comment]
I will "merge" the current Pull Request if that is OK, so I can then remove the 2 Samba Lines in Main.

**Comment by l-arnold** [comment]
@DocCyblade, if you could help the open Merge Request wherein I was trying to remove Samba.  It is hung and needs to be fixed in the Command Line.  (sent info separately).  Thanks for this.  I could not work through the revert.  Was worried I would break something.

**Comment by l-arnold** [comment]
Got the Pull Req complete.
Samba is out. 

In thinking of this in hindsight we would have needed a Update to give "Fileserver" a new unique name as multiple Odoo's would run into each other in that space.

**Comment by l-arnold** [comment]
Removed.  Closing now.  Easy for user (I think) to put back in.  In our history if we want to again.
