### ISSUE TITLE
Safe Merge and Linking with Doc's Beta x builds

### ISSUE THREAD

**Issue by l-arnold** [l-arnold/tkl-nomadic-odoo#39]
I want to see that we, in a merge method, can link back to @DocCyblade , then Branch variations of extra-modules.

This in turn can go to "optional installs" which can start here or root back to @DocCyblade 

 https://github.com/DocCyblade/tkl-odoo/

Somewhat worried about immediate process now..  Likely will require several manual tweaks.

Thoughts @DocCyblade and @JedMeister  ?

**Comment by DocCyblade** [comment]
@l-arnold - This can be done "easy"  by creating a new branch from (https://github.com/l-arnold/tkl-nomadic-odoo/commit/d9e683d15a56f281137e21d4195e3c648e902015) that commit. Because thats when I forked the repo. I then submit a PR to you and you then have a branch that will match mine. I will have to create this branch from the command line as I don't think you can do it with the GitHub web GUI

Let me know if you want to do this

**Comment by DocCyblade** [comment]
I went ahead and created a down stream master and dev (doc-master doc-dev) as long as you don't make commits to these, I can submit pull request each release, that will keep these branches in sync with downstream (tk-odoo)

If you want you can always branch from one and keep changes in a branch off of these. If you make a commit in any of these, auto merge won't work.

I will submit pull request for you to get each up to date with tk-odoo downstream

**Comment by DocCyblade** [comment]
#40 will bring up (https://github.com/l-arnold/tkl-nomadic-odoo/tree/doc-dev) to current dev on downstream. I'll submit a PR for each version I tag so you can keep this branch up to date

**Comment by l-arnold** [comment]
Ok,
How do I run these branches from my side?  Looking like I will accept the Pull Request  that you created into doc-dev.  Not telling me if it will merge or not automatically.

Many changes that is for sure.
This would make it so that I can do general comparisons at least (I suppose I can do that now already just seeing the files changed)

I am OK with accepting this Merge but not even seeing how to do it in web - github.com

---

Never mind.  It looks like it can be merged automatically.
https://github.com/l-arnold/tkl-nomadic-odoo/pull/40

**Comment by l-arnold** [comment]
Was getting "can't automatically be merged" for these on all but the "master" branch.

Exploring a bit though.

**Comment by l-arnold** [comment]
Pulled a new branch "dev-new"  off of Doc-Master.

Now need to reintegrate the Extra Addons.  Mostly there in "dev-old" and "dev-wip1"

Will pull in manually.
