### ISSUE TITLE
First Boot Configuration - Openerp Password

### ISSUE THREAD

**Issue by l-arnold** [l-arnold/tkl-nomadic-odoo#4]
Get
[OK] Stopped PostgreSQL Cluster 9.4 -- main
in middle of "input new password window"

VMWARE

**Comment by l-arnold** [comment]
This is likely related to various Jessie Startup scripts running still after Console Appears.  It basically throws screen garbage in front of the console.  Seems to happen in all sorts of Machine builds.

**Comment by l-arnold** [comment]
Needs both the Password Set and the SED for openerp.conf

Password for odoo needs juss SED.

**Comment by l-arnold** [comment]
Seems we are getting close on this.  Huge Thank you to Ken @DocCyblade

**Comment by l-arnold** [comment]
I think we can close this now.  openerp is now a system user rather than a password user.  OK to close?

**Comment by l-arnold** [comment]
Can reopen if we want to repursue but I like it being system only now.

We should see if we can "su in".  
Also should we make a default folder so one can start/stop openerp-init relatively easily?

**Comment by DocCyblade** [comment]
Not sure what you mean about - folder and  start and stop?

**Comment by l-arnold** [comment]
In Shell one can "manually" control the Odoo Server using
openerp-init  (followed by a few clauses like "start" "stop" "alt config file" etc.  
I believe it lives in the /opt/openerp folder

I ran OpenERP starting and stopping it that way for a year.
in that situation, 
su - openerp
(opened the openerp user into the /opt/openerp folder so it was easy to run the program then exit)

**Comment by DocCyblade** [comment]
ahhh ok. Well with Jessie, they switched from sysinitv to systemd.

Example you used to stop and start Apache like this in sysinit 

```
service apache2 start
```

Now with systemd

```
systemctl start apache2.service
```

You can do the same with openerp/odoo.  Some examples

```
# To stop the service
root@tkl-nomadic-odoo ~# systemctl stop openerp-server.service

# Status of the service when stopped
root@tkl-nomadic-odoo ~# systemctl status openerp-server.service 
* openerp-server.service - LSB: Enterprise Resource Management software
   Loaded: loaded (/etc/init.d/openerp-server)
   Active: inactive (dead) since Thu 2015-09-03 01:06:20 UTC; 14s ago
  Process: 6596 ExecStop=/etc/init.d/openerp-server stop (code=exited, status=0/SUCCESS)
  Process: 4013 ExecStart=/etc/init.d/openerp-server start (code=exited, status=0/SUCCESS)

Sep 02 22:40:00 tkl-nomadic-odoo systemd[1]: Starting LSB: Enterprise Resource Management software...
Sep 02 22:40:00 tkl-nomadic-odoo openerp-server[4013]: Starting openerp-server: openerp-server.
Sep 02 22:40:00 tkl-nomadic-odoo systemd[1]: Started LSB: Enterprise Resource Management software.
Sep 03 01:06:20 tkl-nomadic-odoo systemd[1]: Stopping LSB: Enterprise Resource Management software...
Sep 03 01:06:20 tkl-nomadic-odoo openerp-server[6596]: Stopping openerp-server: openerp-server.
Sep 03 01:06:20 tkl-nomadic-odoo systemd[1]: Stopped LSB: Enterprise Resource Management software.

# Start the service
root@tkl-nomadic-odoo ~# systemctl start openerp-server.service 

# Status of the service when started
root@tkl-nomadic-odoo ~# systemctl status openerp-server.service 
* openerp-server.service - LSB: Enterprise Resource Management software
   Loaded: loaded (/etc/init.d/openerp-server)
   Active: active (running) since Thu 2015-09-03 01:06:54 UTC; 3s ago
  Process: 6596 ExecStop=/etc/init.d/openerp-server stop (code=exited, status=0/SUCCESS)
  Process: 6644 ExecStart=/etc/init.d/openerp-server start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/openerp-server.service
           `-6647 python /opt/openerp/odoo/openerp-server --config=/opt/openerp/odoo/openerp-server.conf --logfile=/var/log/op...

Sep 03 01:06:54 tkl-nomadic-odoo systemd[1]: Starting LSB: Enterprise Resource Management software...
Sep 03 01:06:54 tkl-nomadic-odoo openerp-server[6644]: Starting openerp-server: openerp-server.
Sep 03 01:06:54 tkl-nomadic-odoo systemd[1]: Started LSB: Enterprise Resource Management software.

root@tkl-nomadic-odoo ~#

# Notice it will tell you the pid (if active) how long it's been active or dead
# and then part of the log file at the end.
#
```

Just google Linux systemd and you can find some good reading

**Comment by l-arnold** [comment]
I will explore.  Don't worry about that one.
I think Odoo works pretty much on its own.  

Will learn about system D and your cool stop start process you whipped up today.

If you need an endorsement let me know :)

**Comment by DocCyblade** [comment]
By the way, I used systemd command `systemctl` to stop and start the services

**Comment by l-arnold** [comment]
I was thinking so.  I briefly saw it when I was comparing branches to find out I didn't have the file in my set...  (when I was not seeing the restart services).

Nice move on that one.  I thought it was possible but had not idea how.  I expect others will use that in the future.  Maybe they had.  Anyway.

Uploading an Iso (called beta 01) to the Sourceforge project (good for that anyway)
https://sourceforge.net/projects/tklnomadicodoo/

If you want to have people download an ISO would be an easy path.

Will study systemd and systemctl.  Cool stuff.

**Comment by JedMeister** [comment]
FWIW in Jessie the old sysvinit commands still work too. 

E.g. `/etc/init.d/SERVICE_NAME stop|start|status|etc` still works (for most services);
as does `service SERVICE_NAME stop|start|status|etc`...

**Comment by l-arnold** [comment]
And just clarifying.  Not sure the openerp-init is exactly a service, but it likely starts or stops it.
The service is called openerp-server

Thank you both for your help and insights!  I am a sponge mostly.

**Comment by JedMeister** [comment]
A service is just a program that runs headlessly in the background. E.g. a "windows service". In Linux they are often also known as daemons...

I suspect that that openerp-init is declaring the service (i.e. sets up the openerp-server service). but TBH I'm not sure...

**Comment by DocCyblade** [comment]
Your right on about the file. That does set up the service

**Comment by l-arnold** [comment]
It is funny, a big "milestone" gets achieved.  You think you are all done for a while.  Then you wake up the next morning with a head full of things to do.

I really need to throw down on some other projects  --  though that loops me into  finishing the migration of my data to the beta build.  SSL.  DNS.  Who knows what else.

TKLBAM would be really nice about now moving my SSL etc.  I don't think it is ready for that just now, but it is pulling backups from my prior build.  Might see what happens on a test build.

**Comment by DocCyblade** [comment]
Welcome to software development! It is a never ending job. There is always "the next release"

**Comment by l-arnold** [comment]
OpenERP password, to my understanding, is moot, in the "no password" setup of the System User.
Closing for now.

**Comment by l-arnold** [comment]
Here is a good Link for Odoo Command Line Interface (openerp-init)

https://www.odoo.com/documentation/8.0/reference/cmdline.html
